<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class RegioesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("regioes")->insert([
            ['cidade_id' => 7024,'name' => "Zona 01"],
            ['cidade_id' => 7024,'name' => "Zona 02"],
            ['cidade_id' => 7024,'name' => "Zona 03"],
            ['cidade_id' => 7024,'name' => "Zona 04"],
            ['cidade_id' => 7024,'name' => "Zona 05"],
            ['cidade_id' => 243, 'name' => "Primeira R.A."],
            ['cidade_id' => 243, 'name' => "Segunda R.A."],
            ['cidade_id' => 243, 'name' => "Terceira R.A."],
            ['cidade_id' => 243, 'name' => "Quarta R.A."],
            ['cidade_id' => 243, 'name' => "Quinta R.A."],
            ['cidade_id' => 243, 'name' => "Sexta R.A."],
            ['cidade_id' => 243, 'name' => "Sétima R.A."],
            ['cidade_id' => 243, 'name' => "Oitava R.A."],
            ['cidade_id' => 243, 'name' => "Nona R.A."],
            ['cidade_id' => 2345, 'name' => "Centro"],
            ['cidade_id' => 2345, 'name' => "Leste"],
            ['cidade_id' => 2345, 'name' => "Norte"],
            ['cidade_id' => 2345, 'name' => "Sudeste"],
            ['cidade_id' => 2345, 'name' => "Sul"],
            ['cidade_id' => 1347, 'name' => "Antônio Bezerra"],
            ['cidade_id' => 1347, 'name' => "Barra do Ceará"],
            ['cidade_id' => 1347, 'name' => "Centro"],
            ['cidade_id' => 1347, 'name' => "Mucuripe"],
            ['cidade_id' => 1347, 'name' => "Antônio Bezerra"],
            ['cidade_id' => 1347, 'name' => "Conjunto Ceará"],
            ['cidade_id' => 1347, 'name' => "Cidade dos Funcionários"],
            ['cidade_id' => 1347, 'name' => "Messejana"],
            ['cidade_id' => 1347, 'name' => "Conjunto Ceará"],
            ['cidade_id' => 1347, 'name' => "Prefeito José Walter Mondubim"],
            ['cidade_id' => 1347, 'name' => "Parangaba"],
            ['cidade_id' => 7221, 'name' => "R.A. Norte"],
            ['cidade_id' => 7221, 'name' => "R.A. Sul"],
            ['cidade_id' => 7221, 'name' => "R.A. Leste"],
            ['cidade_id' => 7221, 'name' => "R.A. Oeste"],
            ['cidade_id' => 5198, 'name' => "RPA I"],
            ['cidade_id' => 5198, 'name' => "RPA II"],
            ['cidade_id' => 5198, 'name' => "RPA III"],
            ['cidade_id' => 5198, 'name' => "RPA IV"],
            ['cidade_id' => 5198, 'name' => "RPA V"],
            ['cidade_id' => 5389, 'name' => "RA Centro"],
            ['cidade_id' => 5389, 'name' => "RA Oeste"],
            ['cidade_id' => 5389, 'name' => "RA Norte"],
            ['cidade_id' => 5389, 'name' => "RA Leste"],
            ['cidade_id' => 5406, 'name' => "RPA 01"],
            ['cidade_id' => 5406, 'name' => "RPA 02"],
            ['cidade_id' => 5406, 'name' => "RPA 03"],
            ['cidade_id' => 5406, 'name' => "RPA 04"],
            ['cidade_id' => 5406, 'name' => "RPA 05"],
            ['cidade_id' => 5406, 'name' => "RPA 06"],
            ['cidade_id' => 109, 'name' => "Primeira Região"],
            ['cidade_id' => 109, 'name' => "Segunda Região"],
            ['cidade_id' => 109, 'name' => "Terceira Região"],
            ['cidade_id' => 109, 'name' => "Quarta Região"],
            ['cidade_id' => 109, 'name' => "Quinta Região"],
            ['cidade_id' => 109, 'name' => "Sexta Região"],
            ['cidade_id' => 109, 'name' => "Sétima Região"],
            ['cidade_id' => 109, 'name' => "Oitava Região"],
            ['cidade_id' => 582, 'name' => "Mangabeira"],
            ['cidade_id' => 582, 'name' => "Pampalona"],
            ['cidade_id' => 582, 'name' => "Santana"],
            ['cidade_id' => 582, 'name' => "Santo"],
            ['cidade_id' => 582, 'name' => "Subae"],
            ['cidade_id' => 988, 'name' => "Amaralina"],
            ['cidade_id' => 988, 'name' => "Brotas"],
            ['cidade_id' => 988, 'name' => "Conceição da Praia"],
            ['cidade_id' => 988, 'name' => "Itapoã"],
            ['cidade_id' => 988, 'name' => "Maré"],
            ['cidade_id' => 988, 'name' => "Mares"],
            ['cidade_id' => 988, 'name' => "Nazaré"],
            ['cidade_id' => 988, 'name' => "Paripe"],
            ['cidade_id' => 988, 'name' => "Passo"],
            ['cidade_id' => 988, 'name' => "Penha"],
            ['cidade_id' => 988, 'name' => "Periperi"],
            ['cidade_id' => 988, 'name' => "Pilar"],
            ['cidade_id' => 988, 'name' => "Pirajá"],
            ['cidade_id' => 988, 'name' => "Plataforma"],
            ['cidade_id' => 988, 'name' => "Santana"],
            ['cidade_id' => 988, 'name' => "Santo Antônio"],
            ['cidade_id' => 988, 'name' => "São Caetano"],
            ['cidade_id' => 988, 'name' => "São Cristovão"],
            ['cidade_id' => 988, 'name' => "São Pedro"],
            ['cidade_id' => 988, 'name' => "Sé"],
            ['cidade_id' => 988, 'name' => "Valéria"],
            ['cidade_id' => 988, 'name' => "Vitória"],
            ['cidade_id' => 2741, 'name' => "Primeiro Subdistrito"],
            ['cidade_id' => 2741, 'name' => "Segundo Subdistrito"],
            ['cidade_id' => 2754, 'name' => "Centro-Sul"],
            ['cidade_id' => 2754, 'name' => "Leste"],
            ['cidade_id' => 2754, 'name' => "Nordeste"],
            ['cidade_id' => 2754, 'name' => "Noroeste"],
            ['cidade_id' => 2754, 'name' => "Oeste"],
            ['cidade_id' => 2754, 'name' => "Pampulha"],
            ['cidade_id' => 2754, 'name' => "Venda Nova"],
            ['cidade_id' => 2754, 'name' => "Barreiro"],
            ['cidade_id' => 2754, 'name' => "Oeste"],
            ['cidade_id' => 2754, 'name' => "Nordeste"],
            ['cidade_id' => 2754, 'name' => "Norte"],
            ['cidade_id' => 2754, 'name' => "Pampulha"],
            ['cidade_id' => 2754, 'name' => "Venda Nova"],
            ['cidade_id' => 2762, 'name' => "Ar. Centro"],
            ['cidade_id' => 2762, 'name' => "Ar. Norte"],
            ['cidade_id' => 2762, 'name' => "Ar. Jardim das Alterosas"],
            ['cidade_id' => 2762, 'name' => "Ar. Santa Cruz"],
            ['cidade_id' => 2762, 'name' => "Ar. Imbiruçu"],
            ['cidade_id' => 2762, 'name' => "Ar. Jardim Terezópolis"],
            ['cidade_id' => 2762, 'name' => "Ar. Citrolândia"],
            ['cidade_id' => 2762, 'name' => "Ar. Vianópolis"],
            ['cidade_id' => 2980, 'name' => "Riacho"],
            ['cidade_id' => 2980, 'name' => "Eldorado"],
            ['cidade_id' => 2980, 'name' => "Cinco"],
            ['cidade_id' => 2980, 'name' => "Perobas"],
            ['cidade_id' => 2980, 'name' => "Colorado"],
            ['cidade_id' => 2980, 'name' => "Laguna"],
            ['cidade_id' => 2980, 'name' => "São Joaquim"],
            ['cidade_id' => 2980, 'name' => "Confisco"],
            ['cidade_id' => 2980, 'name' => "Ceasa"],
            ['cidade_id' => 2980, 'name' => "Boa Vista"],
            ['cidade_id' => 2980, 'name' => "Tapera"],
            ['cidade_id' => 2980, 'name' => "Estrela D''alva"],
            ['cidade_id' => 2980, 'name' => "Nacional"],
            ['cidade_id' => 2980, 'name' => "Bom Jesus"],
            ['cidade_id' => 2980, 'name' => "Sede"],
            ['cidade_id' => 2980, 'name' => "VM5"],
            ['cidade_id' => 2980, 'name' => "Bernardo Monteiro"],
            ['cidade_id' => 2980, 'name' => "Petrolândia"],
            ['cidade_id' => 2980, 'name' => "Nova Contagem"],
            ['cidade_id' => 2980, 'name' => "Vargem das Flores"],
            ['cidade_id' => 2980, 'name' => "Cidade Industrial"],
            ['cidade_id' => 2980, 'name' => "Jardim Industrial"],
            ['cidade_id' => 2980, 'name' => "Industrial"],
            ['cidade_id' => 2980, 'name' => "Inconfidentes"],
            ['cidade_id' => 2980, 'name' => "Amazonas"],
            ['cidade_id' => 2980, 'name' => "Bandeirantes"],
            ['cidade_id' => 2980, 'name' => "Riacho"],
            ['cidade_id' => 2980, 'name' => "Jardim Riacho"],
            ['cidade_id' => 2980, 'name' => "Eldorado"],
            ['cidade_id' => 2980, 'name' => "Água Branca"],
            ['cidade_id' => 2985, 'name' => "Região Administrativa 1"],
            ['cidade_id' => 2985, 'name' => "Região Administrativa 2"],
            ['cidade_id' => 2985, 'name' => "Região Administrativa 3"],
            ['cidade_id' => 2985, 'name' => "Região Administrativa 4"],
            ['cidade_id' => 2985, 'name' => "Região Administrativa 5"],
            ['cidade_id' => 2985, 'name' => "Região Administrativa 6"],
            ['cidade_id' => 2985, 'name' => "Região Administrativa 7"],
            ['cidade_id' => 2985, 'name' => "Região Administrativa 8"],
            ['cidade_id' => 3025, 'name' => "Barra"],
            ['cidade_id' => 3245, 'name' => "1 Subdistrito"],
            ['cidade_id' => 3245, 'name' => "Piedade"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial I"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial II"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial III"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial IV"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial V"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial VI"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial VII"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial VIII"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial IX"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial X"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial XI"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial XII"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial XIII"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial XIV"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial XV"],
            ['cidade_id' => 3315, 'name' => "Unidade Territorial XVI"],
            ['cidade_id' => 3641, 'name' => "1 Subdistrito"],
            ['cidade_id' => 3641, 'name' => "2 Sub-Distrito"],
            ['cidade_id' => 3654, 'name' => "Quadrante Central"],
            ['cidade_id' => 3654, 'name' => "Quadrante Nordeste"],
            ['cidade_id' => 3654, 'name' => "Quadrante Centro-Sul"],
            ['cidade_id' => 3654, 'name' => "Quadrante Sudeste"],
            ['cidade_id' => 3654, 'name' => "Quadrante Sudoeste"],
            ['cidade_id' => 3654, 'name' => "Quadrante Noroeste"],
            ['cidade_id' => 3654, 'name' => "Quadrante Industrial"],
            ['cidade_id' => 3986, 'name' => "I Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "II Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "III Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "IV Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "V Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "VI Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "VII Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "VIII Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "IX Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "X Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "XI Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "XII Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "XIII Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "XIV Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "XV Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "XVI Região Administrativa"],
            ['cidade_id' => 3986, 'name' => "XVII Região Administrativa"],
            ['cidade_id' => 4047, 'name' =>  "Dea Maria"],
            ['cidade_id' => 4047, 'name' =>  "Distrito Industrial II"],
            ['cidade_id' => 4047, 'name' =>  "Bougainville"],
            ['cidade_id' => 4047, 'name' =>  "Parque Empresarial"],
            ['cidade_id' => 4047, 'name' =>  "Parque Tecnologico"],
            ['cidade_id' => 4047, 'name' =>  "Fabricio"],
            ['cidade_id' => 4047, 'name' =>  "Boa Vista"],
            ['cidade_id' => 4047, 'name' =>  "Lageado"],
            ['cidade_id' => 4047, 'name' =>  "Amoroso Costa"],
            ['cidade_id' => 4047, 'name' =>  "Portal"],
            ['cidade_id' => 4047, 'name' =>  "Alfredo Freire"],
            ['cidade_id' => 4047, 'name' =>  "Distrito Industrial I"],
            ['cidade_id' => 4047, 'name' =>  "Grande Horizonte"],
            ['cidade_id' => 4047, 'name' =>  "Mercês"],
            ['cidade_id' => 4047, 'name' =>  "Centro"],
            ['cidade_id' => 4047, 'name' =>  "Boa Esperança"],
            ['cidade_id' => 4047, 'name' =>  "Estados Unidos"],
            ['cidade_id' => 4047, 'name' =>  "Paraíso"],
            ['cidade_id' => 4047, 'name' =>  "Morumbi"],
            ['cidade_id' => 4047, 'name' =>  "Aeroporto"],
            ['cidade_id' => 4047, 'name' =>  "Santa Maria"],
            ['cidade_id' => 4047, 'name' =>  "São Benedito"],
            ['cidade_id' => 4047, 'name' =>  "Abadia"],
            ['cidade_id' => 4047, 'name' =>  "Leblon"],
            ['cidade_id' => 4047, 'name' =>  "Costa Teles"],
            ['cidade_id' => 4047, 'name' =>  "Lourdes"],
            ['cidade_id' => 4047, 'name' =>  "Jochey Park"],
            ['cidade_id' => 4047, 'name' =>  "Parque das Américas"],
            ['cidade_id' => 4047, 'name' =>  "São Cristóvão"],
            ['cidade_id' => 4047, 'name' =>  "Vallim"],
            ['cidade_id' => 4047, 'name' =>  "Santa Clara"],
            ['cidade_id' => 4047, 'name' =>  "2000"],
            ['cidade_id' => 4047, 'name' =>  "São Geraldo"],
            ['cidade_id' => 4047, 'name' =>  "Recreio dos Bandeirantes"],
            ['cidade_id' => 4047, 'name' =>  "Maracanã"],
            ['cidade_id' => 4047, 'name' =>  "Vila Real"],
            ['cidade_id' => 2028, 'name' => "Região do Civit"],
            ['cidade_id' => 2028, 'name' => "Região de Serra Sede"],
            ['cidade_id' => 2028, 'name' => "Região de Serra Sede"],
            ['cidade_id' => 2028, 'name' => "Região de Jacaraípe e Manguinhos"],
            ['cidade_id' => 2028, 'name' => "Região de Carapina"],
            ['cidade_id' => 2028, 'name' => "Região de Anchieta"],
            ['cidade_id' => 2028, 'name' => "Região de Laranjeiras"],
            ['cidade_id' => 2028, 'name' => "Região do Civit"],
            ['cidade_id' => 2028, 'name' => "Região de Nova Almeida"],
            ['cidade_id' => 2028, 'name' => "Região de Jacaraípe e Manguinhos"],
            ['cidade_id' => 2044, 'name' => "Centro"],
            ['cidade_id' => 2044, 'name' => "Grande Aribiri"],
            ['cidade_id' => 2044, 'name' => "Grande Ibes"],
            ['cidade_id' => 2044, 'name' => "Grande Aribiri"],
            ['cidade_id' => 2044, 'name' => "Grande Cobilândia"],
            ['cidade_id' => 2044, 'name' => "Grande Aribiri"],
            ['cidade_id' => 2044, 'name' => "Grande Cobilândia"],
            ['cidade_id' => 2044, 'name' => "Grande Ibes"],
            ['cidade_id' => 2044, 'name' => "Grande Jucu"],
            ['cidade_id' => 2044, 'name' => "Grande Aribiri"],
            ['cidade_id' => 2044, 'name' => "Grande Cobilândia"],
            ['cidade_id' => 2048, 'name' => "Região Administrativa I - Centro"],
            ['cidade_id' => 2048, 'name' => "Região Administrativa II - Santo Antônio"],
            ['cidade_id' => 2048, 'name' => "Região Administrativa III - Bento Ferreira/Jucutuquara"],
            ['cidade_id' => 2048, 'name' => "Região Administrativa IV - Maruípe"],
            ['cidade_id' => 2048, 'name' => "Região Administrativa V - Praia do Canto"],
            ['cidade_id' => 2048, 'name' => "Região Administrativa VII - São Pedro"],
            ['cidade_id' => 2048, 'name' => "Região Administrativa VI - Continente"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa I"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa II"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa III"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa IV"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa V"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa VI"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa VII"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa VIII"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa IX"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa X"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa XI"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa XII"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa XIII"],
            ['cidade_id' => 6863, 'name' => "Região Administrativa XIV"],
            ['cidade_id' => 6865, 'name' => "Areia Branca"],
            ['cidade_id' => 6865, 'name' => "Nova Aurora"],
            ['cidade_id' => 6865, 'name' => "Jardim Redentor"],
            ['cidade_id' => 6865, 'name' => "Parque São José"],
            ['cidade_id' => 6865, 'name' => "Lote XV"],
            ['cidade_id' => 6885, 'name' => "Primeira Região Administrativa (Centro)"],
            ['cidade_id' => 6885, 'name' => "Segunda Região Administrativa (Ubás)"],
            ['cidade_id' => 6885, 'name' => "Terceira Região Administrativa (Rodagem)"],
            ['cidade_id' => 6885, 'name' => "Quarta Região Administrativa (Praia de Carapebus)"],
            ['cidade_id' => 6881, 'name' => "Primeiro Subdistrito"],
            ['cidade_id' => 6881, 'name' => "Segundo Subdistrito"],
            ['cidade_id' => 6881, 'name' => "Terceiro Subdistrito"],
            ['cidade_id' => 6881, 'name' => "Quarto Subdistrito"],
            ['cidade_id' => 6932, 'name' => "Sub-região da Orla"],
            ['cidade_id' => 6932, 'name' => "Sub-região do Arrastão das Pedras"],
            ['cidade_id' => 6932, 'name' => "Sub-região de Sapeatiba"],
            ['cidade_id' => 6932, 'name' => "Sub-região Área da Lagoa"],
            ['cidade_id' => 6955, 'name' => "Japeri"],
            ['cidade_id' => 6955, 'name' => "Engenheiro Pedreira"],
            ['cidade_id' => 6955, 'name' => "Marajoara"],
            ['cidade_id' => 6955, 'name' => "Rio D''Ouro"],
            ['cidade_id' => 6955, 'name' => "Pedra Lisa"],
            ['cidade_id' => 6962, 'name' => "Barra de Macaé"],
            ['cidade_id' => 6962, 'name' => "Aeroporto"],
            ['cidade_id' => 6962, 'name' => "Cabiúnas"],
            ['cidade_id' => 6962, 'name' => "Imboassica"],
            ['cidade_id' => 6962, 'name' => "Centro"],
            ['cidade_id' => 6962, 'name' => "Nova Cidade"],
            ['cidade_id' => 6994, 'name' => "Unidade Regional de Governo Centro - URG I"],
            ['cidade_id' => 6994, 'name' => "Unidade Regional de Governo da Posse - URG II"],
            ['cidade_id' => 6994, 'name' => "Unidade Regional de Governo de Comendador Soares - URG III"],
            ['cidade_id' => 6994, 'name' => "Unidade Regional de Governo de Cabuçu - URG VII"],
            ['cidade_id' => 6994, 'name' => "Unidade Regional de Governo de Km 32 - URG VIII"],
            ['cidade_id' => 6994, 'name' => "Unidade Regional de Governo de Austim - URG IX"],
            ['cidade_id' => 6994, 'name' => "Unidade Regional de Governo de Vila de Cava - URG X"],
            ['cidade_id' => 6994, 'name' => "Unidade Regional de Governo de Miguel Couto - URG XI"],
            ['cidade_id' => 6994, 'name' => "U.R.G. de Tinguá,Adrianópolis,Rio D''Ouro e Jaceruba-URG XII"],
            ['cidade_id' => 7031, 'name' => "Centro"],
            ['cidade_id' => 7031, 'name' => "Nordeste"],
            ['cidade_id' => 7031, 'name' => "Leste"],
            ['cidade_id' => 7031, 'name' => "Sul"],
            ['cidade_id' => 7031, 'name' => "Oeste"],
            ['cidade_id' => 7031, 'name' => "Norte"],
            ['cidade_id' => 7031, 'name' => "Industrial"],
            ['cidade_id' => 7043, 'name' => "Portuária"],
            ['cidade_id' => 7043, 'name' => "Centro"],
            ['cidade_id' => 7043, 'name' => "Rio Comprido"],
            ['cidade_id' => 7043, 'name' => "Botafogo"],
            ['cidade_id' => 7043, 'name' => "Copacabana"],
            ['cidade_id' => 7043, 'name' => "Lagoa"],
            ['cidade_id' => 7043, 'name' => "São Cristovão"],
            ['cidade_id' => 7043, 'name' => "Tijuca"],
            ['cidade_id' => 7043, 'name' => "Vila Isabel"],
            ['cidade_id' => 7043, 'name' => "Ramos"],
            ['cidade_id' => 7043, 'name' => "Penha"],
            ['cidade_id' => 7043, 'name' => "Méier"],
            ['cidade_id' => 7043, 'name' => "Irajá"],
            ['cidade_id' => 7043, 'name' => "Madureira"],
            ['cidade_id' => 7043, 'name' => "Jacarepaguá"],
            ['cidade_id' => 7043, 'name' => "Bangu"],
            ['cidade_id' => 7043, 'name' => "Campo Grande"],
            ['cidade_id' => 7043, 'name' => "Santa Cruz"],
            ['cidade_id' => 7043, 'name' => "Ilha do Governador"],
            ['cidade_id' => 7043, 'name' => "Ilha de Paquetá"],
            ['cidade_id' => 7043, 'name' => "Anchieta"],
            ['cidade_id' => 7043, 'name' => "Santa Teresa"],
            ['cidade_id' => 7043, 'name' => "Barra da Tijuca"],
            ['cidade_id' => 7043, 'name' => "Pavuna"],
            ['cidade_id' => 7043, 'name' => "Guaratiba"],
            ['cidade_id' => 7043, 'name' => "Inhaúma"],
            ['cidade_id' => 7043, 'name' => "Rocinha"],
            ['cidade_id' => 7043, 'name' => "Jacarezinho"],
            ['cidade_id' => 7043, 'name' => "Complexo do Alemão"],
            ['cidade_id' => 7043, 'name' => "Maré"],
            ['cidade_id' => 7043, 'name' => "Realengo"],
            ['cidade_id' => 7043, 'name' => "Cidade de Deus"],
            ['cidade_id' => 7043, 'name' => "Vigário Geral"],
            ['cidade_id' => 7078, 'name' => "Região Sul"],
            ['cidade_id' => 7078, 'name' => "Região Norte"],
            ['cidade_id' => 7078, 'name' => "Região Oeste"],
            ['cidade_id' => 7078, 'name' => "Região Leste"],
            ['cidade_id' => 5914, 'name' => "Zona 1"],
            ['cidade_id' => 5914, 'name' => "Zona 2"],
            ['cidade_id' => 5914, 'name' => "Zona 3"],
            ['cidade_id' => 5914, 'name' => "Zona 4"],
            ['cidade_id' => 5914, 'name' => "Zona 5"],
            ['cidade_id' => 6015, 'name' => "Administração Regional da Matriz (R.1.MZ)"],
            ['cidade_id' => 6015, 'name' => "Administração Regional do Boqueirão (R.2.BQ)"],
            ['cidade_id' => 6015, 'name' => "Administração Regional do Cajuru (R.3.CJ)"],
            ['cidade_id' => 6015, 'name' => "Administração Regional da Boa Vista (R.4.BV)"],
            ['cidade_id' => 6015, 'name' => "Administração Regional de Santa Felicidade (R.5.SF)"],
            ['cidade_id' => 6015, 'name' => "Administração Regional do Portão (R.7.PR)"],
            ['cidade_id' => 6015, 'name' => "Administração Regional Pinheirinho (R.8.PN)"],
            ['cidade_id' => 6015, 'name' => "Administração Regional do Bairro Novo (R.10.BN)"],
            ['cidade_id' => 6268, 'name' => "Centro"],
            ['cidade_id' => 6268, 'name' => "Região Norte"],
            ['cidade_id' => 6268, 'name' => "Região Oeste"],
            ['cidade_id' => 6268, 'name' => "Região Leste"],
            ['cidade_id' => 6268, 'name' => "Região Sul"],
            ['cidade_id' => 6308, 'name' => "Zona 1"],
            ['cidade_id' => 6308, 'name' => "Zona 2"],
            ['cidade_id' => 6308, 'name' => "Zona 3"],
            ['cidade_id' => 6308, 'name' => "Zona 4"],
            ['cidade_id' => 6308, 'name' => "Zona 5"],
            ['cidade_id' => 6308, 'name' => "Zona 6"],
            ['cidade_id' => 6308, 'name' => "Zona 7"],
            ['cidade_id' => 6308, 'name' => "Zona 8"],
            ['cidade_id' => 6308, 'name' => "Zona 9"],
            ['cidade_id' => 6308, 'name' => "Zona 10"],
            ['cidade_id' => 6308, 'name' => "Zona 11"],
            ['cidade_id' => 6308, 'name' => "Zona 12"],
            ['cidade_id' => 6308, 'name' => "Zona 13"],
            ['cidade_id' => 6308, 'name' => "Zona 14"],
            ['cidade_id' => 6308, 'name' => "Zona 15"],
            ['cidade_id' => 6308, 'name' => "Zona 17"],
            ['cidade_id' => 6308, 'name' => "Zona 18"],
            ['cidade_id' => 6308, 'name' => "Zona 19"],
            ['cidade_id' => 6308, 'name' => "Zona 20"],
            ['cidade_id' => 6308, 'name' => "Zona 21"],
            ['cidade_id' => 6308, 'name' => "Zona 22"],
            ['cidade_id' => 6308, 'name' => "Zona 23"],
            ['cidade_id' => 6308, 'name' => "Zona 24"],
            ['cidade_id' => 6308, 'name' => "Zona 25"],
            ['cidade_id' => 6308, 'name' => "Zona 26"],
            ['cidade_id' => 6308, 'name' => "Zona 27"],
            ['cidade_id' => 6308, 'name' => "Zona 28"],
            ['cidade_id' => 6308, 'name' => "Zona 29"],
            ['cidade_id' => 6308, 'name' => "Zona 30"],
            ['cidade_id' => 6308, 'name' => "Zona 31"],
            ['cidade_id' => 6308, 'name' => "Zona 35"],
            ['cidade_id' => 6308, 'name' => "Zona 36"],
            ['cidade_id' => 6308, 'name' => "Zona 37"],
            ['cidade_id' => 6308, 'name' => "Zona 38"],
            ['cidade_id' => 6308, 'name' => "Zona 39"],
            ['cidade_id' => 6308, 'name' => "Zona 40"],
            ['cidade_id' => 6308, 'name' => "Zona 41"],
            ['cidade_id' => 6308, 'name' => "Zona 42"],
            ['cidade_id' => 6308, 'name' => "Zona 43"],
            ['cidade_id' => 6308, 'name' => "Zona 44"],
            ['cidade_id' => 6308, 'name' => "Zona 45"],
            ['cidade_id' => 6308, 'name' => "Zona 46"],
            ['cidade_id' => 6308, 'name' => "Zona 47"],
            ['cidade_id' => 6308, 'name' => "Zona 48"],
            ['cidade_id' => 6308, 'name' => "Zona Central"],
            ['cidade_id' => 6308, 'name' => "Zona 34"],
            ['cidade_id' => 6308, 'name' => "Zona 33"],
            ['cidade_id' => 7396, 'name' => "Zona Central"],
            ['cidade_id' => 7396, 'name' => "Zona da Coxilha ou Cidade Alta"],
            ['cidade_id' => 7396, 'name' => "Zona Norte"],
            ['cidade_id' => 7396, 'name' => "Zona Sul"],
            ['cidade_id' => 7396, 'name' => "Zona Leste"],
            ['cidade_id' => 7396, 'name' => "Zona Oeste"],
            ['cidade_id' => 7408, 'name' => "MZ1- Centro"],
            ['cidade_id' => 7408, 'name' => "MZ2- Americana / Sumaré"],
            ['cidade_id' => 7408, 'name' => "MZ3- Bela Vista"],
            ['cidade_id' => 7408, 'name' => "MZ4- Intersul"],
            ['cidade_id' => 7408, 'name' => "MZ5- Algarve"],
            ['cidade_id' => 7408, 'name' => "MZ6- Aparecida"],
            ['cidade_id' => 7408, 'name' => "MZ7- Cocão"],
            ['cidade_id' => 7408, 'name' => "MZ8- Piratini"],
            ['cidade_id' => 7408, 'name' => "MZ9- Formosa / Maria Regina"],
            ['cidade_id' => 7408, 'name' => "MZ10- Umbu"],
            ['cidade_id' => 7408, 'name' => "MZ10- Umbu"],
            ['cidade_id' => 7408, 'name' => "MZ 11 - Industrial"],
            ['cidade_id' => 7566, 'name' => "RA 01 - Centro"],
            ['cidade_id' => 7566, 'name' => "RA 02 - Santa Lúcia"],
            ['cidade_id' => 7566, 'name' => "RA 03 - Fátima"],
            ['cidade_id' => 7566, 'name' => "RA 04 - Cruzeiro"],
            ['cidade_id' => 7566, 'name' => "RA 05 - Esplanada"],
            ['cidade_id' => 7566, 'name' => "RA 06 - Rizzo"],
            ['cidade_id' => 7566, 'name' => "RA 07 - Forqueta"],
            ['cidade_id' => 7566, 'name' => "RA 08 - Ana Rech"],
            ['cidade_id' => 7566, 'name' => "RA 09 - Galópolis"],
            ['cidade_id' => 7566, 'name' => "RA 10 - Serrano"],
            ['cidade_id' => 7566, 'name' => "RA 11 - Planalto"],
            ['cidade_id' => 7566, 'name' => "RA 12 - Presidente Vargas"],
            ['cidade_id' => 7566, 'name' => "RA 13 - São Giácomo"],
            ['cidade_id' => 7566, 'name' => "RA 14 - Nossa Senhora da Saúde"],
            ['cidade_id' => 7566, 'name' => "RA 15 - Santa Fé"],
            ['cidade_id' => 7591, 'name' => "Área de Planejamento 01"],
            ['cidade_id' => 7656, 'name' => "Sede"],
            ['cidade_id' => 7656, 'name' => "Caveiras"],
            ['cidade_id' => 7656, 'name' => "Vacaiquá"],
            ['cidade_id' => 7656, 'name' => "Ponche Verde"],
            ['cidade_id' => 7656, 'name' => "Fontouras"],
            ['cidade_id' => 7697, 'name' => "Leste"],
            ['cidade_id' => 7697, 'name' => "Norte"],
            ['cidade_id' => 7697, 'name' => "Oeste"],
            ['cidade_id' => 7697, 'name' => "Sul"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Centro 'Centro e Vila Vergueiro'"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Boqueirão"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Vera Cruz"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Petrópolis"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro São Luiz Gonzaga"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro 'Vila Cruzeiro'"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Lucas de Araújo"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Santa Marta"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Integração"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro 'Vila Vitor Issler'"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro São José"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro São Cristóvão"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Roselândia"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro 'Vila Mattos'"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Annes 'Vila Fátima e Vila Annes'"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro José Alexandre Zachia"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Valinhos 'Loteamento Industrial e São Lucas'"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro 'Vila Luíza'"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro 'Vila Rodrigues'"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro 'Vila Santa Maria'"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Planaltina"],
            ['cidade_id' => 7953, 'name' => "Região do Bairro Nenê Graeff"],
            ['cidade_id' => 7965, 'name' => "Três Vendas"],
            ['cidade_id' => 7965, 'name' => "Barragem"],
            ['cidade_id' => 7965, 'name' => "Fragata"],
            ['cidade_id' => 7965, 'name' => "Centro"],
            ['cidade_id' => 7965, 'name' => "Areal"],
            ['cidade_id' => 7965, 'name' => "Laranjal/Z3"],
            ['cidade_id' => 7965, 'name' => "São Gonçalo"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 01"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 02"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 03"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 04"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 05"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 06"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 07"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 08"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 09"],
            ['cidade_id' => 8041, 'name' => "UNidade Censitária 10"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 11"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 12"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 13"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 14"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 15"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 16"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 17"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 18"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 19"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 20"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 21"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 22"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 23"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 24"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 25"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 26"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 27"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 28"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 29"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 30"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 31"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 32"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 33"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 34"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 35"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 36"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 37"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 38"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 41"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 42"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 40"],
            ['cidade_id' => 8041, 'name' => "Unidade Censitária 39"],
            ['cidade_id' => 6586, 'name' => "Centro Urbano"],
            ['cidade_id' => 6586, 'name' => "Norte"],
            ['cidade_id' => 6586, 'name' => "Nordeste"],
            ['cidade_id' => 6586, 'name' => "Leste"],
            ['cidade_id' => 6586, 'name' => "Centro-Leste"],
            ['cidade_id' => 6586, 'name' => "Sul"],
            ['cidade_id' => 6586, 'name' => "Centro-Oeste"],
            ['cidade_id' => 6586, 'name' => "Oeste"],
            ['cidade_id' => 8104, 'name' => "Uplans 1"],
            ['cidade_id' => 8104, 'name' => "Uplans 2"],
            ['cidade_id' => 8104, 'name' => "Uplans 3"],
            ['cidade_id' => 8104, 'name' => "Uplans 4"],
            ['cidade_id' => 8104, 'name' => "Uplans 5"],
            ['cidade_id' => 8104, 'name' => "Uplans 6"],
            ['cidade_id' => 8104, 'name' => "Uplans 7"],
            ['cidade_id' => 8104, 'name' => "Uplans 8"],
            ['cidade_id' => 8104, 'name' => "Uplans 9"],
            ['cidade_id' => 8104, 'name' => "Uplans 10"],
            ['cidade_id' => 8104, 'name' => "Uplans 11"],
            ['cidade_id' => 8104, 'name' => "Uplans 12"],
            ['cidade_id' => 8104, 'name' => "Uplans 13"],
            ['cidade_id' => 8104, 'name' => "Uplans 14"],
            ['cidade_id' => 8104, 'name' => "Uplans 15"],
            ['cidade_id' => 8104, 'name' => "Uplans 16"],
            ['cidade_id' => 8104, 'name' => "Uplans 17"],
            ['cidade_id' => 8104, 'name' => "Uplans 18"],
            ['cidade_id' => 8143, 'name' => "Núcleo Cidade Baixa"],
            ['cidade_id' => 8143, 'name' => "Núcleo São José do Norte-Sul"],
            ['cidade_id' => 8143, 'name' => "Núcleo São José do Norte-Norte"],
            ['cidade_id' => 8143, 'name' => "Núcleo Centro Histórico"],
            ['cidade_id' => 8143, 'name' => "Núcleo Barra-Molhe Leste"],
            ['cidade_id' => 8143, 'name' => "Núcleo Zona Rural"],
            ['cidade_id' => 8143, 'name' => "Núcleo do Segundo Distrito"],
            ['cidade_id' => 8143, 'name' => "Núcleo do Terceiro Distrito"],
            ['cidade_id' => 4141, 'name' => "Região Urbana do Centro"],
            ['cidade_id' => 4141, 'name' => "Região Urbana do Prosa"],
            ['cidade_id' => 4141, 'name' => "Região Urbana do Segredo"],
            ['cidade_id' => 4141, 'name' => "Região Urbana do Imbirussú"],
            ['cidade_id' => 4141, 'name' => "Região Urbana do Anhanduizinho"],
            ['cidade_id' => 4141, 'name' => "Região Urbana do Bandeira"],
            ['cidade_id' => 4141, 'name' => "Região Urbana do Lagoa"],
            ['cidade_id' => 4226, 'name' => "Setor Vilela"],
            ['cidade_id' => 4226, 'name' => "Setor Ypê"],
            ['cidade_id' => 4226, 'name' => "Setor Centro"],
            ['cidade_id' => 4226, 'name' => "Setor Aeroporto"],
            ['cidade_id' => 4226, 'name' => "Setor Marambaia"],
            ['cidade_id' => 4347, 'name' => "Administração Regional Norte"],
            ['cidade_id' => 4347, 'name' => "Administração Regional Centro-Oeste"],
            ['cidade_id' => 4347, 'name' => "Administração Regional Centro-Leste"],
            ['cidade_id' => 4347, 'name' => "Administração Regional Norte"],
            ['cidade_id' => 4347, 'name' => "Administração Regional Centro-Leste"],
            ['cidade_id' => 4347, 'name' => "Administração Regional Sul-Leste"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Central"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Sul"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Marista"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Oeste"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Aeroporto"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Norte Ferroviário"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Vila Nova"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Leste Universitário"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jardim Goiás"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Alto da Glória e Redenção"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Santo Antonio"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Pedro Ludovico/Bela Vista/Jardins das Esmeraldas"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Bueno"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Nova Suiça"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Parque Amazônia"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jardim América"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Sudoeste"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Cidade Jardim"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Coimbra"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Campinas"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Aeroviários"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Marechal Rondon"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Criméia Leste"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Negrão de Lima"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Bairro Feliz"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jardim Novo Mundo"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Riviera/Água Branca"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Autódromo ou Parque Lozandes"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Parque das Laranjeiras e Jardim da Luz"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jardim Atlântico"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jardim Europa"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Novo Horizonte/Faiçalville"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Celina Park/Recreio dos Funcionários"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Caravelas"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Baliza-Itaipu"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Parque Santa Rita"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Parque Oeste Industrial"],
            ['cidade_id' => 2174, 'name' => "U.T.P. João Braz"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Vila Rizzo"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Parque Bom Jesus"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Vera Cruz"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jardim Petrópolis"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Vila Regina/Parque Industrial Paulista/Santos Dumont"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Cândida de Morais/Maria Dilce"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Capuava"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Urias Magalhães"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Goiânia II"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Santa Genoveva"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Aeroporto Internacional Santa Genoveva"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jaó"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Santo Hilário"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Vila Pedroso"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Chácaras São Joaquim"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Mutirão e Curitiba"],
            ['cidade_id' => 2174, 'name' => "U.T.P. São Domingos"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Finsocial"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jardim Balneário Meia Ponte/Mansões Goianas"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Campus Universitário/Conjunto Itatiaia"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Vila Jardim São Judas Tadeu/Jardim Pompéia"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jardim Guanabara"],
            ['cidade_id' => 2174, 'name' => "U.T.P. CEASA/Aldeia do Vale"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Jardim Primavera (Área Urbana Isolada)"],
            ['cidade_id' => 2174, 'name' => "U.T.P. Zona Rural"],
            ['cidade_id' => 1778, 'name' => "Brasília"],
            ['cidade_id' => 1778, 'name' => "Gama"],
            ['cidade_id' => 1778, 'name' => "Taguatinga"],
            ['cidade_id' => 1778, 'name' => "Brazlândia"],
            ['cidade_id' => 1778, 'name' => "Sobradinho"],
            ['cidade_id' => 1778, 'name' => "Planaltina"],
            ['cidade_id' => 1778, 'name' => "Paranoá"],
            ['cidade_id' => 1778, 'name' => "Riacho Fundo"],
            ['cidade_id' => 1778, 'name' => "Núcleo Bandeirante"],
            ['cidade_id' => 1778, 'name' => "Ceilândia"],
            ['cidade_id' => 1778, 'name' => "Guará"],
            ['cidade_id' => 1778, 'name' => "Cruzeiro"],
            ['cidade_id' => 1778, 'name' => "Samambaia"],
            ['cidade_id' => 1778, 'name' => "Candangolândia"],
            ['cidade_id' => 1778, 'name' => "Recanto das Emas"],
            ['cidade_id' => 1778, 'name' => "Lago Norte"],
            ['cidade_id' => 1778, 'name' => "Lago Sul"],
            ['cidade_id' => 1778, 'name' => "Santa Maria"],
            ['cidade_id' => 1778, 'name' => "São Sebastião"],
        ]);
    }
}
